### ISSUE TITLE
PicoDVI fails to compile on pico-sdk 2.2.0

### ISSUE THREAD

**Issue by arlaneenalra** [Wren6991/PicoDVI#91]
Just ran into the this trying to compile with pico-sdk 2.2.0. 
```
[ 86%] Building ASM object apps/hello_dvi/CMakeFiles/hello_dvi.dir/__/__/libdvi/tmds_encode.S.o
/Users/jules/code/rp2040/pico-sdk/src/boards/include/boards/pico.h: Assembler messages:
/Users/jules/code/rp2040/pico-sdk/src/boards/include/boards/pico.h:17: Error: bad instruction `pico_board_cmake_set(PICO_PLATFORM, rp2040)'
/Users/jules/code/rp2040/pico-sdk/src/boards/include/boards/pico.h:75: Error: bad instruction `pico_board_cmake_set_default(PICO_FLASH_SIZE_BYTES, (2*1024*1024))'
gmake[2]: *** [apps/hello_dvi/CMakeFiles/hello_dvi.dir/build.make:935: apps/hello_dvi/CMakeFiles/hello_dvi.dir/__/__/libdvi/tmds_encode.S.o] Error 1
```

Comparing https://github.com/raspberrypi/pico-sdk/blame/2.1.1/src/boards/include/boards/pico.h and https://github.com/raspberrypi/pico-sdk/blame/2.2.0/src/boards/include/boards/pico.h

It looks like https://github.com/raspberrypi/pico-sdk/commit/fed7188e527baa922f4130b90b39dc64e3dd8eef is the culprit.  In particular, the error points to the new macros(?):
* pico_board_cmake_set
* pico_board_cmake_set_default

To reproduce:
* clone the pico-sdk checked out to the 2.2.0 tag
I'm using this to setup a build, 
```
#!/usr/bin/env bash
set -e

# Find the directory of the script file
# See: https://stackoverflow.com/a/246128
DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

#####
### Set path to pico-sdk here:
export PICO_SDK_PATH=/path/to/pico-sdk

export BUILD_TYPE=Release

BUILD_DIR=${DIR}/build
SOURCE_DIR=${DIR}/software


get_core_count() {
  if [[ "$(uname -s || true)" == "Darwin" ]]; then
    sysctl -n hw.ncpu
  else
    cat /proc/cpuinfo | grep processor | wc -l
  fi
}

setup() {
  export PICO_PLATFORM
  export PICO_BOARD
  export DVI_DEFAULT_SERIAL_CONFIG
  
  TARGET_DIR=${PICO_PLATFORM:-$PICO_BOARD}

  export BUILD_DIR=${DIR}/build/${TARGET_DIR}

  echo "Building for ${TARGET_DIR}" 

  cmake -E make_directory ${BUILD_DIR}

  (
    cd  ${BUILD_DIR}

    cmake ${SOURCE_DIR} \
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
      -DPICO_COPY_TO_RAM=1 \
      -DDVI_DEFAULT_SERIAL_CONFIG=${DVI_DEFAULT_SERIAL_CONFIG} \
      -DPICO_PLATFORM=${PICO_PLATFORM}

    cmake --build . \
      --config $BUILD_TYPE \
      --parallel $(get_core_count)
  )
}

PICO_PLATFORM=rp2040 DVI_DEFAULT_SERIAL_CONFIG=adafruit_feather_dvi_cfg setup 
``

But that's mostly to set: `PICO_PLATFORM=rp2040 DVI_DEFAULT_SERIAL_CONFIG=adafruit_feather_dvi_cfg` for the build.

Seems to work fine if I switch back to pico-sdk 2.1.1. I'm not sure if the bug is in PicoDVI or the SDK right now.

**Comment by fhoedemakers** [comment]
@Wren6991 has solved this: https://github.com/Wren6991/PicoDVI/commit/feb371bf1a6c170c281a4b079f2b42539828a4d9
pull the latest version of the master branch and it should compile fine.

**Comment by arlaneenalra** [comment]
Confirmed! Glad it was that simple :)
